dist: trusty
sudo: required

language: android

jdk:
  - openjdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

env:
  global:
    secure: "PVbL8+paUZtJKEgWqq+Z73WZ00TKGJv26R1GDauhdoA8tMawYYy499JNFo6VUd0TSbYbPEvejJmS8d6V2fu5cnROrvweiiAsDoHOXXFIHPbQEzqE1cJqcIilsdR4YFP3SQ7Hv6SI/HVDxWkRAxgjvFjUSIGcnJqCAw/VffNlVhs="

script:
  - ./gradlew evaluateViolations testDebugUnitTest assembleDebug -s

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android
