language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26

jdk:
  - oraclejdk8

before_script:
  - echo "org.gradle.configureondemand=true" >> $HOME/.gradle/gradle.properties
  - echo "org.gradle.jvmargs=-Xmx1536M" >> $HOME/.gradle/gradle.properties
  
script: "./gradlew build"

env:
  global:
    secure: "PVbL8+paUZtJKEgWqq+Z73WZ00TKGJv26R1GDauhdoA8tMawYYy499JNFo6VUd0TSbYbPEvejJmS8d6V2fu5cnROrvweiiAsDoHOXXFIHPbQEzqE1cJqcIilsdR4YFP3SQ7Hv6SI/HVDxWkRAxgjvFjUSIGcnJqCAw/VffNlVhs="

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android
